#!/bin/bash

FILE_SIZE=15728640,31457280,47185920,57671680
RUN_COUNT=1
INSTANCES=4
LEECH_COUNT=2
PASSIVE_COUNT=0
LATENCY=5
JITTER=10
BANDWIDTH=100
PARALLEL_GEN=100
TESTCASE=transfer

source ./exec.sh

run $TESTCASE $INSTANCES $FILE_SIZE $RUN_COUNT $LATENCY $JITTER $PARALLEL_GEN $LEECH_COUNT $BANDWIDTH
# BANDWIDTH=150
# INSTANCES=7
# LEECH_COUNT=3
# run $TESTCASE $INSTANCES $FILE_SIZE $RUN_COUNT $LATENCY $JITTER $PARALLEL_GEN $LEECH_COUNT $BANDWIDTH

# BANDWIDTH=150
# INSTANCES=7
# LEECH_COUNT=1
# run $TESTCASE $INSTANCES $FILE_SIZE $RUN_COUNT $LATENCY $JITTER $PARALLEL_GEN $LEECH_COUNT $BANDWIDTH

# python process.py --plots latency messages overhead throughput
